### PR TITLE
PR: Update plugin for spyder 4 API

### PR DESCRIPTION
**Pull request by goanpeca**
Screen Shot 2020-03-05 at 20 02 55
Screen Shot 2020-03-05 at 20 02 39

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 this is using a "dummy dockwidget"  that was the original fix Nodd made to get this to work. 

I don't understand how to use the `SpyderPlugin`class, as it was not working for me.

Thoughts?

**Comment by ccordoba12** [comment]
> I don't understand how to use the SpyderPluginclass, as it was not working for me.

Why is not working for you? I mean, in what sense?

**Comment by CAM-Gerlach** [comment]
> I don't understand how to use the SpyderPluginclass, as it was not working for me.

@ccordoba12 Sounds like the average issue report on the Spyder bug tracker :rofl:

**Comment by JosepVirgili** [comment]
Tested with Spyder 4.1.5 and can confirm that it works. However this error is raised at startup:
```
    plugin.dockwidget.remove_title_bar()
AttributeError: 'DummyDock' object has no attribute 'remove_title_bar'
```

**Comment by peendebak** [comment]
@ccordoba12 @goanpeca The PR branch is unavailable on github: `goanpeca wants to merge 1 commit into spyder-ide:master from unknown repository` . How to I checkout and test this PR?

**Comment by ccordoba12** [comment]
Sorry but it seems @goanpeca decided to remove his fork. Fortunately, auto-formatting is supported out of the box by Spyder **4.2.0**, so this extra plugin is not necessary anymore.

To format a file or selection you need to go the menu `Source > Format file or selection` or press the shortcut `Ctrl + Alt + I` (`Cmd + Alt + I` in macOS).

**Pull request closed without merging**
